### ISSUE TITLE
Crash when trying to render document containing Unicode character

### ISSUE THREAD

**Issue by certifiedwaif** [oprdyn/publish#32]
This seems to be triggered by using `&darr;` on Mac OS X via the Docker container.

```
➜  notes git:(master) ✗ ./build.sh run
05:36:35Z (00000.005) Identify .book file
05:36:35Z (00000.005) relative = "./"
05:36:35Z (00000.005) bookfile = "Meeting_Notes.book"
05:36:35Z (00000.009) Read .book file
05:36:35Z (00000.023) fragments = 4
05:36:35Z (00000.023) Setup temporary directory
05:36:35Z (00000.029) tmpdir = "/tmp/publish-CnuVqN"
05:36:35Z (00000.029) Convert document fragments to LaTeX
05:36:35Z (00000.029) source = "Meeting_Notes/Meeting_Andrew_and_Anth_2019_03_12.md"
05:36:35Z (00000.033) target = "/tmp/publish-CnuVqN/Meeting_Notes/Meeting_Andrew_and_Anth_2019_03_12.latex"
05:36:35Z (00000.182) /tmp/publish-CnuVqN/Meeting_Notes/Meeting_Andrew_and_Anth_2019_03_12.latex: commitAndReleaseBuffer: invalid argument (invalid character)
```

**Comment by afcowie** [comment]
Thanks for the report. My hypothesis is that the problem is related to the encoding on the host's filesystem not supporting UTF-8 (lol wot) without `$inset_special_config_here`. I'm trying to reproduce this on a Linux system but it's being suspiciously tolerant.

**Comment by afcowie** [comment]
Ok. I've been able to replicate the problem by doing this
```haskell
    withFile target WriteMode $ \handle -> do
        hSetEncoding handle latin1
```
which results in
```
11:38:19Z (00000.017) /tmp/publish-elMoQK/Strike.latex: commitAndReleaseBuffer: invalid argument (invalid character)
```

Changing the code to
```haskell
    withFile target WriteMode $ \handle -> do
        hSetEncoding handle utf8
```
makes the problem go away (except that I never had it, as such).

I found this [post](https://www.reddit.com/r/haskell/comments/43tmt8/commitbuffer_invalid_argument_invalid_character/czkxv6t/) which references a VM running "in the wrong locale" which seems analogous to the situation you found yourself in running under Docker-for-Mac's docker-machine VM. That post suggests an alternative to set the locale for the whole program:

```haskell
import GHC.IO.Encoding

main = do
    setLocaleEncoding utf8
    ...
```
which may or may not be the right thing.

**Comment by afcowie** [comment]
Ah. Found a way to reproduce. It is indeed locale related:
```shell
$ LANG=en_US ./render ...
11:46:48Z (00000.017) /tmp/publish-MIvayh/Strike.latex: commitAndReleaseBuffer: invalid argument (invalid character)
```
Bang.

In that scenario, setting the "locale" to `utf8` as above indeed fixes the problem.

**Comment by certifiedwaif** [comment]
The fix that @afcowie pushed seems to resolve the problem.
