### ISSUE TITLE
Consider changing Level 1 headers from chapter to section

### ISSUE THREAD

**Issue by afcowie** [oprdyn/publish#42]
Level 1 headers (ATX style `#` SE style `====`) are at present mapped through to being `\chapter`s. This is has done well to date but I have started to notice a few patterns:

In most document fragments, there is at most one H1, acting as [triggering a] chapter title. This has meant an immediate appeal to `\part` in larger documents in order to create structure. In smaller documents, meanwhile, there is again only one level 1 header, essentially wasting it to make a page title.

It may be that we would be better off changing the level 1 mapping from chapter to section and manually issuing `\chapter` commands as we manually issue `\part` commands if and when necessary.

This would enable document fragment authors to more freely combine documents together without leading to the pattern that each stub heading is a blank chapter.

AfC

**Comment by afcowie** [comment]
This would mean a fair bit of surgery to existing documents in order to maintain table of contents coherence and pagination (especially in collections of short stories and poems).

**Comment by JimCooke** [comment]
I support this idea as my own documentation has many self-contained pages that markdownlint will require to start with a H1.  However, in stitching them together in a book like I use this tool for, it isn't always appropriate to have a new chapter for every topic (for example, I have several discussions on BASH commands ... "BASH Commands" might be the chapter, rather than individual commands themselves).  Will give me a bit more control over the look and feel of printed documents.

**Comment by afcowie** [comment]
At present Pandoc embellishes headings as follows

```text
Conclusion
========
```

becomes

```text
\hypertarget{conclusion}{%
\chapter{Conclusion}\label{conclusion}}
```

so people will need to do that manually for chapter and part level entries. This seems acceptable. 

[this is only so the hyperlink in the table of contents works. Not clear if label is actually also needed for that use case.]

**Comment by certifiedwaif** [comment]
I agree with @JimCooke, I would prefer greater control. And I think a new chapter and a top-level heading are separate concepts.

**Comment by afcowie** [comment]
Thanks for your comments. I have several large manuscripts that I'll have to convert; I'll use those as a testbed this weekend and if it's good merge #43. I'm guessing the only real hassle might turn out to be the impact on existing expectations for `\tableofcontents*` output but there are settings knobs there.
